name: leace
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - transformers
  - datasets
  - spacy
  - scikit-learn
  - numpy
  - tqdm
  - pip:
    - conllu 
    - concept_erasure
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl
  - matplotlib

