name: leace
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - transformers
  - datasets
  - spacy
  - scikit-learn
  - numpy
  - tqdm
  - pip:
    - conllu #for UD 
    - concept_erasure
  - matplotlib

